### ISSUE TITLE
Any way to swap artist and track labels?

### ISSUE THREAD

**Issue by pschfr** [sveint/spotify-notify#8]
I would prefer for the name of the track I'm listening to to be on top, with the artist name and album below. Is there any way I can change this?
![screenshot_2015-08-26_12-15-51](https://cloud.githubusercontent.com/assets/490222/9499260/7ce8621e-4bec-11e5-908b-07c55ad7d85a.png)

**Comment by sveint** [comment]
That probably makes more sense, but I don't have time to fix it now.

You can simply swap the lines at https://github.com/sveint/spotify-notify/blob/master/spotify-notify.py#L154

**Comment by sveint** [comment]
That probably makes more sense, I have committed a fix to master branch.
